service: graphql
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
package:
  include:
    - node_modules/**
    - schema.js

plugins:
  - serverless-offline

functions:
  graphql:
    handler: handler.graphql
    events:
      - http:
          path: graphql
          method: post
          cors: false
      - http:
          path: graphql
          method: get
          cors: false
  graphiql:
    handler: handler.graphiql
    events:
      - http:
          path: graphiql
          method: get
